export const MEMBER_PREFIX  = '#MEMBER_';
export const MEMBER_LOAD_SUCCESS = '##MEMBER_LOAD_SUCCESS';
export const MEMBER_ADD_SUCCESS = '#MEMBER_ADD_SUCCESS';
export const MEMBER_UPDATE_SUCCESS = '#MEMBER_UPDATE_SUCCESS';
export const MEMBER_DELETE_SUCCESS = '#MEMBER_DELETE_SUCCESS';