export const MOVIE_LOAD_SUCCESS = 'MOVIE_LOAD_SUCCESS';
export const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS';
export const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS';
export const MOVIE_DELETE_SUCCESS =  'MOVIE_DELETE_SUCCESS';
export const MOVIE_CLEAR_PERSISTED = "MOVIE_CLEAR_PERSISTED";